### ISSUE TITLE
[Korekto][TP1] première séance à compléter avant le 10/02/2020 23h00

### ISSUE THREAD

**Issue by ledoyen** [YanisLa/TP-java-alpha#8]
Votre exercice n'est pas complet :
* Badge Codecov manquant dans le fichier [README.md](https://github.com/YanisLa/TP-java-alpha/blob/master/README.md) : [![codecov](https://codecov.io/gh/yanisla/tp-java-alpha/branch/master/graph/badge.svg)](https://codecov.io/gh/yanisla/tp-java-alpha)

Rappel du sujet : https://github.com/ledoyen/tp-java/blob/master/projet/4A_2020/TP.md.  
Vous avez jusqu'au 10/02/2020 23h pour ajouter et/ou corriger ces erreurs.  
Au delà de cette date, la première séance de TP sera considérée incomplète et la note du projet sera réduite de 2 points.

**Comment by YanisLa** [comment]
Bonjour,

Nous sommes au colloc, pouvez vous s’il vous plaît nous accorder jusqu’au lundi 10 ? La connexion est très mauvaise ici.


Yanis LARBI
Etudiant Ingénieur - 4ème année
ESIEA Paris
________________________________
De : Loïc Ledoyen <notifications@github.com>
Envoyé : mardi 4 février 2020 01:11:45
À : YanisLa/TP-java-alpha <TP-java-alpha@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [YanisLa/TP-java-alpha] [Korekto][TP1] première séance à compléter avant le 07/03/2020 (#8)


Votre exercice n'est pas complet :

  *   Badge Codecov manquant dans le fichier README.md<https://github.com/YanisLa/TP-java-alpha/blob/master/README.md> : [codecov] <https://codecov.io/gh/yanisla/tp-java-alpha>

Rappel du sujet : https://github.com/ledoyen/tp-java/blob/master/projet/4A_2020/TP.md.
Vous avez jusqu'au 07/02/2020 pour ajouter et/ou corriger ces erreurs.
Au delà de cette date, la première séance de TP sera considérée incomplète et la note du projet sera réduite de 2 points.

**Comment by ledoyen** [comment]
L'exercice est maintenant complet
